spring.application.name=Silicon_Val_Game

spring.datasource.url=jdbc:postgresql://localhost:5432/silicon_valley_trail_db
spring.datasource.username=postgres
spring.datasource.password=Silicon
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true